### ISSUE TITLE
opencensus/copts.bzl build error

### ISSUE THREAD

**Issue by jinmel** [census-instrumentation/opencensus-cpp#304]
bazel build //examples/grpc/...:all
INFO: Invocation ID: d03519eb-4a29-427c-b063-751b4799b838
ERROR: /home/vagrant/opencensus-cpp/opencensus/copts.bzl:24:1: file '@com_google_absl//absl:copts/configure_copts.bzl' does not contain symbol 'LLVM_FLAGS'
ERROR: /home/vagrant/opencensus-cpp/opencensus/copts.bzl:37:35: Traceback (most recent call last):
        File "/home/vagrant/opencensus-cpp/opencensus/copts.bzl", line 36
                select({"//opencensus:llvm_compiler": (...)})
        File "/home/vagrant/opencensus-cpp/opencensus/copts.bzl", line 37, in select
                LLVM_FLAGS
name 'LLVM_FLAGS' is not defined
ERROR: /home/vagrant/opencensus-cpp/opencensus/copts.bzl:42:14: name 'DEFAULT_COPTS' is not defined
ERROR: error loading package 'examples/grpc': Extension file 'opencensus/copts.bzl' has errors
INFO: Elapsed time: 0.276s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)
    currently loading: examples/grpc

there is an error within opencensus/copts.bzl

**Comment by jinmel** [comment]
#307
